### ISSUE TITLE
Enhance new package location selector

### ISSUE THREAD

**Issue by ismaaffiya** [upmind-automation/provision-provider-shared-hosting#44] opened 2024-02-07 03:24 UTC
Support Enhance's new package location selection integration so that customers can select a location during checkout that corresponds to the location in Enhance when adding a service

**Comment by qublify** [comment] 2024-02-16 14:25
Hi, any updates on this? Would be ideal if this could be supported ASAP.

**Comment by clearhost-cmd** [comment] 2024-02-16 14:47
We need this ASAP our customers cannot select locations currently!

**Comment by mendozal** [comment] 2024-02-16 15:04
If would be great if this feature is supported in the Upmind-Enhance integration.

**Comment by uphlewis** [comment] 2024-02-19 15:30
Duplicate of #39

**Closed** 2024-02-19 19:25 UTC
Labels: enhancement
